--- #YAML:1.0
name:                   WWW-Scraper-ISBN-Amazon_Driver
version:                0.11
abstract:               Search drivers for the Amazon online catalog.
author:
  - Barbie <barbie@cpan.org>

license:                perl
distribution_type:      module
installdirs:            site

requires:
  Template::Extract:    0
  Test::More:           0.45
  WWW::Mechanize:       0
  WWW::Scraper::ISBN:   0.25
  WWW::Scraper::ISBN::Driver: 0.18
recommends:
  Test::More:           0.45
  Test::Pod:            1.00
  Test::Pod::Coverage:  0.08
  Test::YAML::Meta:     0
build_requires:
  Test::More:           0.45

provides:
  WWW::Scraper::ISBN::AmazonUK_Driver:
    file:     lib/WWW/Scraper/ISBN/AmazonUK_Driver.pm
    version:  0.11
  WWW::Scraper::ISBN::AmazonUS_Driver:
    file:     lib/WWW/Scraper/ISBN/AmazonUS_Driver.pm
    version:  0.11
no_index:
  directory:
    - t
    - examples

meta-spec:
   version:   1.3
   url:       http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: Hand 1.0

