--- #YAML:1.0
name:                   WWW-Scraper-ISBN-Amazon_Driver
version:                0.36
abstract:               Search drivers for the Amazon online catalog.
author:
  - Barbie <barbie@cpan.org>

license:                artistic_2
distribution_type:      module
installdirs:            site

requires:
  perl:                         5.006
  JSON:                         0
  WWW::Mechanize:               1.60
  WWW::Scraper::ISBN:           0.25
  WWW::Scraper::ISBN::Driver:   0.18
recommends:
  Test::CPAN::Meta:             0
  Test::CPAN::Meta::JSON:       0
  Test::Pod:                    1.00
  Test::Pod::Coverage:          0.08
build_requires:
  Data::Dumper:                 0
  IO::File:                     0
  Test::More:                   0.70

provides:
  WWW::Scraper::ISBN::Amazon_Driver:
    file:     lib/WWW/Scraper/ISBN/Amazon_Driver.pm
    version:  0.36
  WWW::Scraper::ISBN::AmazonUK_Driver:
    file:     lib/WWW/Scraper/ISBN/AmazonUK_Driver.pm
    version:  0.36
  WWW::Scraper::ISBN::AmazonUS_Driver:
    file:     lib/WWW/Scraper/ISBN/AmazonUS_Driver.pm
    version:  0.36
no_index:
  directory:
    - t
    - examples

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=WWW-Scraper-ISBN-Amazon_Driver
  repository: http://github.com/barbie/www-scraper-isbn-amazon_driver

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0

